## Uses a GH worker token so that ‘Version Packages’ PRs trigger downstream workflows (GITHUB_TOKEN-created PRs do not).
## https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'blockprotocol/blockprotocol'
    environment: main
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Get token
        id: app-token
        uses: hashintel/.github/.github/actions/github-app-token@8c1a3b18a4f6528fc8eabcf9acda7780a1e47776 # main
        with:
          vault-address: ${{ vars.VAULT_ADDR }}
          vault-role: ci-blockprotocol-release
          app-id: "4505139"
          transit-key: github-app-block-protocol-release
          repository: ${{ github.repository }}
          cf-access-client-id: ${{ vars.CF_ACCESS_CLIENT_ID }}
          cf-access-client-secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: ./.github/actions/warm-up-repo

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@c8bada60c408975afd1a20b3db81d6eee6789308 # v1.4.9
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
